---
version: '3'
services:
  base:
    image: mobile_suit_base
    build:
      context: ./images
      dockerfile: base/Dockerfile
    entrypoint: sleep 1
  emacs:
    image: mobile_suit_emacs
    build:
      context: ./images
      dockerfile: emacs/Dockerfile
    container_name: emacs
    environment:
      - DISPLAY=$ip:0
    stdin_open: true
    tty: true
    volumes:
      - git:/home/emacs/code
  groovy:
    image: mobile_suit_groovy
    build:
      context: ./images
      dockerfile: groovy/Dockerfile
    container_name: groovy
    tty: true
    volumes:
      - git:/home/emacs/code
volumes:
  git:
    external: true
