---
version: '3'

mobile_suit_context: &build_context ./images
mobile_suit_volumes: &volumes
  - git:/home/emacs/code
mobile_suit_images: &images

services:
  base:
    build:
      context: *build_context
      dockerfile: base/Dockerfile
      entrypoint: sleep 1
  emacs:
    build:
      context: *build_context
      dockerfile: emacs/Dockerfile
    container_name: emacs
    environment:
      - DISPLAY=$ip:0
      - TZ=EST
    links: *images
    stdin_open: true
    tty: true
    volumes: *volumes
volumes:
  git:
    external: true
