---
version: '3'
mobile_suit_volumes: &volumes
  - git:/home/emacs/code
services:
  base:
    build:
      context: ./images
      dockerfile: base/Dockerfile
      entrypoint: sleep 1
  emacs:
    build:
      context: ./images
      dockerfile: emacs/Dockerfile
    container_name: emacs
    environment:
      - DISPLAY=$ip:0
      - TZ=EST
    stdin_open: true
    tty: true
    volumes: *volumes
  groovy:
    build:
      context: ./images
      dockerfile: groovy/Dockerfile
    container_name: groovy
    ports:
      - "22"
    stdin_open: true
    tty: true
    volumes: *volumes

volumes:
  git:
    external: true
